### ISSUE TITLE
reveal activity behind the project on the site - ideas?

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5please#180]
web platform is a moving target so with html5please we have a need to keep up. 

one of the challenges with content for developers is to prove that you're devoted to keeping it up to date.

I think we're doing pretty good with that on html5please (but it could always be better) .. but really we could surface our activity and work to the site a little better

this led me to start this lazyweb req a while ago: h5bp/lazyweb-requests#57

it led to a few possibilities:
- http://jsfiddle.net/gnclmorais/aUUTJ/75/
- http://tylerlh.github.com/github-latest-commits-widget/?username=jquery&repo=jquery&limit=20

I think in our case we want something more minimal in both content and presentation.. 

Also not sure how to integrate it.. top/right, in the footer somehow?

Would love to hear any thoughts anyone has here.

**Comment by evverx** [comment]
@arthurvr , it doesn't work in Firefox 35.01 and Safari 7.1. I fix it in #353 .
