### ISSUE TITLE
Flexbox: USE? Are you sure?

### ISSUE THREAD

**Issue by zanona** [h5bp/html5please#291]
I am not quite sure if this is the place to relate about this but apparently a [Flexbox search](http://html5please.com/#flexbox) points us to USE the Flexbox CSS feature.

There is no observation, like: Use with a fallback, or anything like it.

I am also not sure on how you are dealing with it, but being supported only on IE10+ are you sure you should recommend people to simply use Flexbox without any warning?

Some more basic features such as [background-image](http://html5please.com/#background) which aren't supported by IE8 are clearly defining that it should be used with a fallback.

So I am just wondering how Flexbox is marked as free to use as it would work anywhere?

**Comment by arthurvr** [comment]
> I think we're in agreement. A PR to put this to use with fallback or not recommended with the information here would be very welcome.

@zanona @KraigWalker A PR would be really welcome :)

**Comment by stuartpb** [comment]
I think autoprefixer with something like https://github.com/stuartpb/mozboxie is probably good enough to make flexbox usable.

**Comment by bradleyflood** [comment]
Agreed. I was surprised to see `flexbox` with a full *Use* status.
Yet taking that advice I did go ahead and use it on a complex project only to find that though there is support for all modern browsers I did discover notable differences in how FireFox, Chrome and IE handle flexbox's various properties when flexboxes are nested. In the end I had to do some slight hacking to get it to work the same in all these browsers (in their latest versions). 
So in my opinion *Use* is a bit ambitious perhaps?

**Comment by shreeshkatyayan** [comment]
Another year hence, started with Angular Material framework. The nested flexbox would be astonishingly different in case of FF and Safari. Then I modified https://github.com/leejordan/reflex and used it, having inline-block fallback for older browsers. Currently, I am using the old specifications fallback. Almost all web browsers work fine now. UC Browser(12% user base for me) and FF Mobile (negligible) still cannot handle flex system. Both the fallbacks don't work in these browsers. Any heads up?
