### ISSUE TITLE
Rethink project architecture

### ISSUE THREAD

**Issue by arthurvr** [h5bp/html5please#336]
I think we all agree that there are some problems with current project architecture:
- **We need a (better) build task.** The current code live on html5please.com is totally working, but can be optimised in so many ways. For example:
  - It isn't serving minified html
  - It's not concatenating javascript files together. However, [it should be](https://github.com/h5bp/html5please/blob/master/template.html#L93).
  - It's not serving minified CSS
  - Not huge of a problem, but some files shouldn't end up being online. Our [`.editorconfig`](http://html5please.com/.editorconfig) for example.
- **We need file watchers.** Right now, when doing development, you need to run the compass watch task but you also need to run `node ./lib/` every time you change something to the actual content or to `template.html`.
- **We need some kind of build-in server** For most of us bumping up a local server isn't difficult, but for others it might not be. I would like to be able to use Livereload too.
- **Linting** Right now we aren't using any code linting/formatting which results in mixed tabs and spaces, [missing semicolons](https://github.com/h5bp/html5please/commit/1053c9d46809fb10b28b583debee1d45092b742f), [unnecessary semicolons](https://github.com/h5bp/html5please/commit/4df6084cea166b25d0e7ad8e06c08f940ed1fa23), ...
- **Autoprefixer** I would like to include some kind of automatic prefixing, so we don't need to care about things like [this](https://github.com/h5bp/html5please/blob/master/css/sass/style.scss#L8) anymore.
- **Tests**

---

My suggestion to handle all of this:
- Grunt is already included, but we're not using its power. I would like to let grunt/gulp handle the prefixing, linting, server, ...
- Include a build task, powered by grunt/gulp, doing all the things a good build system does. It would generate a `build/` directory.
- I would handle the deployment just like the `html5boilerplate.com` repo. Travis runs the build task and puts it into a `server-content`. Than we can let the server periodically pull the new commits in that branch. I don't really know who owns the server used? Is it @paulirish?
- I would opt to use gulp for all of this (instead of grunt), but of course I'm open for discussion. Also see the discussion in https://github.com/h5bp/html5-boilerplate/pull/1563.
- I would be able to handle all of this
- I would like to replace the logic inside new_feature.sh with node. It's cross platform. (Done in https://github.com/h5bp/html5please/commit/2cead4e0d5cd484e72e29e4dd02909291be775fc)

---

Thoughts? 

(I'm just added to the `html5please` team. Hellow!)

(Cc: @h5bp/html5please)

**Comment by arthurvr** [comment]
The current styles are basically a mess. Y'all alright with the following things?

* [ ] Remove compass in favor of autoprefixer, as we currently only use it for prefixing. We could update to libsass while I'm on it.
* [ ] Update the `scss` files to adhere the code styling specified in [the style guide we have for Effeckt](https://github.com/h5bp/Effeckt.css/wiki/Code-Style-Guide)?
* [ ] Modularize all styles by splitting them up in different files (currently we have a mess of 700 lines long)

**Comment by paulirish** [comment]
yesssssssss​
