### ISSUE TITLE
Revisit ES6 post

### ISSUE THREAD

**Issue by arthurvr** [h5bp/html5please#342]
Maybe it's time to revisit the post on ES6? Some points worth discussing/changing:

* I don't know how up-to-date https://gist.github.com/Raynos/1665192 still is?

* In the post we state that ES6 to ES3 compilers aren't ready to use. Some are these days. Isn't it? Are there maybe some nice blogposts about ES6 to ES3 workflows we could link to?

* The `moreurl` we're using is only about modules. Isn't there something more general?

* Maybe we should give some more info about how the future is looking for ES6? What's going to land soon? What will need much more time? What browsers are already upon it?

**Comment by tx5** [comment]
@arthurvr WHY U NO LIKE ISSUES ??

**Comment by tx5** [comment]
@arthurvr WHY U NO LIKE ISSUES ??
