### ISSUE TITLE
Suggestion about Font loading performance.

### ISSUE THREAD

**Issue by hzlmn** [h5bp/html5please#362]
Right for now everytime when page refreshing fonts reloaded. My suggestion to add caching fonts with local storage. Gist https://gist.github.com/hdragomir/8f00ce2581795fd7b1b7. I want to know your opinion about it, is it makes sense?

**Comment by davidyezsetz** [comment]
I've used this technique before and it works quite well. So generally I'd support it, but I would measure it to see how much you really get out of it.

**Comment by coliff** [comment]
I'm not so sure about adding JavaScript for this. The Google Font is loaded from a fast CDN so instead I think it's more helpful to add preconnect to https://fonts.gstatic.com/ in the page head. I've just done that in a PR now.

**Comment by mischah** [comment]
> You should not store fonts using localStorage or IndexedDB; each of those has its own set of performance issues. The browser's HTTP cache provides the best and most robust mechanism to deliver font resources to the browser.

See [Google Web Fundamentals](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=en#proper_caching_is_a_must)
