### ISSUE TITLE
Responsive images srcset attribute

### ISSUE THREAD

**Issue by louh** [h5bp/html5please#367]
Hello!  Any plans to support information for the image `srcset` attribute?

http://caniuse.com/#feat=srcset
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

Let me know if there's anything I can do to help.

**Comment by arthurvr** [comment]
SGTM. :+1:

**Comment by drichardson** [comment]
Any reason this hasn't been merged back into h5bp/html5please?

**Comment by mischah** [comment]
PR #370 needs review.

Yep. That took a while …
