### ISSUE TITLE
Site last updated undefined.

### ISSUE THREAD

**Issue by RyanZim** [h5bp/html5please#383]
At the bottom of [html5please.com](http://html5please.com/), It says

> Site last updated undefined.

Looks like you are printing an undefined JavaScript variable.

**Comment by mischah** [comment]
Uhm. The last change is just to long ago :see_no_evil:

`pretty.js` returns `undefined` when the last change is older than a month.
See https://github.com/h5bp/html5please/blob/master/src/js/libs/pretty.js#L14

Going to fix that now :blush:
