### ISSUE TITLE
Do you need help maintaining this?

### ISSUE THREAD

**Issue by mischah** [h5bp/html5please#385]
Hej,

it seems like nothing happened here for quite a while. I check back from time time because of my open PR #375 …

Is there no maintenance intended ? That would be sad. Because it’s still a valuable resource.
Therefore I would like to offer my help with maintenance. 

Are you interested?

@arthurvr @paulirish @connor @nimbupani

**Comment by paulirish** [comment]
Yup! I've added you to the repo. Your help with the project would be totallly awesome

**Comment by mischah** [comment]
> Yup! I've added you to the repo.

Great :sparkling_heart: 

>  Your help with the project would be totallly awesome

My pleasure :octocat:

**Comment by alrra** [comment]
@mischah Welcome to the team! :tada:

**Comment by mischah** [comment]
Thanks @alrra :kissing:
