### ISSUE TITLE
Enable squash merging for this repo

### ISSUE THREAD

**Issue by mischah** [h5bp/html5please#389]
Hej @h5bp/html5please,

could someone with admin privileges enable squash merging as described over here:
https://github.com/blog/2141-squash-your-commits

Thanks,
Michael

**Comment by paulirish** [comment]
wasn't me, but it appears to be on: 

![image](https://cloud.githubusercontent.com/assets/39191/14229046/5596e7da-f8ee-11e5-9020-bc1b2c07b32a.png)

**Comment by mischah** [comment]
Thanks to whoever it was :sparkling_heart:
