### ISSUE TITLE
update google analytics script

### ISSUE THREAD

**Issue by coliff** [h5bp/html5please#444]
suggest to remove the `ga.js` implementation which is deprecated now and instead use the simpler, faster-loading async-enabled `analytics.js` (as used on html5boilerplate):
https://github.com/h5bp/html5-boilerplate/blob/master/src/index.html

I can open a PR for this...

**Comment by mischah** [comment]
> I can open a PR for this.

👍

**Comment by mischah** [comment]
This is done with #453 right?

**Comment by coliff** [comment]
yup. I'll close this now. thanks!
