### ISSUE TITLE
Remove IE6 and IE7 info

### ISSUE THREAD

**Issue by coliff** [h5bp/html5please#445]
IE6 and IE7 marketshare is just 0.01%. https://caniuse.com/usage-table

I suggest removing all references to these versions from the documents and from the selector at top of the homepage.

IE8/9/10's marketshare is also really tiny (as IE11 is available on Windows 7, 8.1 and 10).

Shall I open a PR to remove IE6 and IE7 info and keep IE8/9/10 for now?

**Comment by mischah** [comment]
Hej @coliff,

I thought about that in the context of #409. But unfortunately I can’t remember the final outcome 😂 

Let me think again:

- IE6 and 7 can be removed without a doubt. 
- I would say the same thing regarding IE8 and IE9
- IE10 is pretty exotic but still supported until January 31, 2020

Personal notes: 
- We only have to support IE11 in new projects
- But is info regarding older versions valuable for people who have to support legacy web applications?

I personally tend to say to keep IE8/9/10 for while.

**Comment by coliff** [comment]
Yes, I agree with your comments. Let's proceed with just removing IE6 & IE7 for now. If you can review and merge my PR for the fixed URLs I'll make a new PR for this.
P.S. I'm on the HTML5Boilerplate team and would be very happy to help out more here. If I could have access to make branches and add tags etc.... if you agree can you add me (if you have access)?

**Comment by mischah** [comment]
I would really appriciate your help :octocat: 

Im not able to add you by myself for now. But requested to add you over here:
https://github.com/orgs/h5bp/teams/html5please/discussions/1

Let’s see how this will work out.

**Comment by coliff** [comment]
thanks! hopefully @roblarsen can add me.

**Comment by roblarsen** [comment]
@coliff @mischah I'll add you now. I didn't actually see the request earlier (I'm not actually on that team.)

**Comment by coliff** [comment]
thanks Rob 👍

**Comment by roblarsen** [comment]
No worries. Let me know if you need anything else. 

As an aside, I'm working on the h5bp organization page these days and am looking to add a "help wanted" section. If you label issues "help-wanted" I should be able to pull them in and publicize them on Twitter.  

I'm really trying to promote and cultivate active repos in the org this year.
