### ISSUE TITLE
Remove minmaxwh ?

### ISSUE THREAD

**Issue by coliff** [h5bp/html5please#460]
I suggest to remove min/max-width/height section altogether. It has 99.99% browser coverage (of tracked browsers) and has been supported since IE7. I think it's so obvious it's safe to use that it isn't needed on the site.
REF: https://caniuse.com/#feat=minmaxwh

**Comment by mischah** [comment]
Yep. Good catch 👌🏼
Relates to #409

**Comment by mischah** [comment]
Hej @coliff, are you going to do tackle this? 

Otherwise I would assign this issue to myself 😗

**Comment by coliff** [comment]
I don't mind either way - pls feel free to do it if you like.
