### ISSUE TITLE
Show moreurl and caniuse link together

### ISSUE THREAD

**Issue by mischah** [h5bp/html5please#462]
Right now the link to caniuse.com link is replaced by a »Learn more« pointing to the `moreurl` in case the latter one is used.

Example:
* https://html5please.com/#vibration
* https://github.com/h5bp/html5please/blob/master/posts/vibration.md

This doesn’t make sense to me and must be a bug, right?

**Comment by coliff** [comment]
yep, looks like a bug - happening on https://html5please.com/#ecmascript too
